export const departments = [
  "Agricultural Economics",
  "Agricultural Extension",
  "Animal Science and Technology",
  "Crop Science and Technology",
  "Fisheries and Aquaculture Technology",
  "Forestry and Wildlife Technology",
  "Soil Science and Technology",
  "Biochemistry",
  "Biology",
  "Biotechnology",
  "Microbiology",
  "Forensic Science",
  "Computer Engineering (CME)",
  "Electrical (Power Systems) Engineering (EPE)",
  "Electronics Engineering (ELE)",
  "Mechatronics Engineering (MCE)",
  "Telecommunications Engineering (TCE)",
  "Electrical and Electronic Engineering (EEE)",
  "Agricultural and Bioresource Engineering (ABE)",
  "Biomedical Engineering (BME)",
  "Chemical Engineering (CHE)",
  "Civil Engineering (CIE)",
  "Food Science and Technology (FST)",
  "Materials and Metallurgical Engineering (MME)",
  "Mechanical Engineering (MEE)",
  "Mechatronics Engineering (MCE)",
  "Petroleum Engineering (PET)",
  "Polymer and Textile Engineering (PTE)",
  "Dental Technology",
  "Environmental Health Science",
  "Optometry",
  "Prosthetics and Orthodontics",
  "Public Health Technology",
  "Computer Science Department (CSC)",
  "Cyber Security Department (CYB)",
  "Information Technology Department (IFT)",
  "Software Engineering Department (SOE)",
  "Entrepreneurship and Innovation",
  "Logistics and Transport Technology",
  "Maritime Technology and Logistics",
  "Logistics and Supply Chain Management",
  "Project and Management Technology",
  "Chemistry",
  "Geology",
  "Mathematics",
  "Physics",
  "Science Laboratory Technology",
  "Statistics",
  "Human Anatomy",
  "Human Physiology",
  "Architecture",
  "Building Technology",
  "Environmental Management",
  "Quantity Surveying",
  "Surveying and Geoinformatics",
  "Urban and Regional Planning",
  "Environmental Management and Evaluation",
];


export const shopCategories = [
  "Food & Beverage",
  "Clothing & Accessories",
  "Books & Stationery",
  "Electronics & Accessories",
  "Health & Beauty",
  "Events & Entertainment",
  "Secondhand Goods",
  "Services",
  "Tech Services",
];
