export const users = [
  {
    name: "Chidera Okoro",
    picture: "https://randomuser.me/api/portraits/men/1.jpg",
    kingdom: "Umuchima",
    location: {
      longitude: 6.987654,
      latitude: 5.394321,
    },
    username: "chidera_oko",
    status: "student",
    level: 200,
    department: "MEE",
    title: [
      "CEO Ebony Footies",
      "Family Head , Public Health",
      "President NFCS Lectors FUTO chapter",
    ],
    about:
      "Welcome to Ebony Footies , we designa and deliver all kinds of flash footwears , for you and yours",
    shops: [
      {
        id: 300,
        name: "Book Nook",
        description: "Books and stationeries for students.",
        longitude: 6.986272042631102,
        latitude: 5.396506567461426,
        size: 0.0007,
        userId: 3,
        category: "Education",
        occupied: true,
      },
      {
        id: 4,
        name: "Fashion Hub",
        description: "Trendy clothes and accessories.",
        longitude: 5.397906567461426,
        latitude: 6.989072042631102,
        size: 0.0007,
        userId: 4,
        category: "Fashon & Design",
        occupied: true,
      },
      {
        id: 1221,
        name: "Gadget World",
        description: "Mobile phones and accessories.",
        longitude: 6.993972042631103,
        latitude: 5.396506567461426,
        size: 0.0007,
        userId: 2,
        categoryId: 2,
        category: "Gadgets & Home Appliances",
        occupied: true,
      },
    ],
  },
  {
    name: "Adaobi Nnaji",
    picture: "https://randomuser.me/api/portraits/women/2.jpg",
    kingdom: "Eziobodo",
    location: {
      longitude: 6.984522042631101,
      latitude: 5.400356567461427,
    },
    username: "adaobi_nnaji",
  },
  {
    name: "Ifeanyi Uche",
    picture: "https://randomuser.me/api/portraits/men/3.jpg",
    kingdom: "Ihiagwa",
    location: {
      longitude: 7.001322042631105,
      latitude: 5.393356567461425,
    },
    username: "ifeanyi_001",
  },
  {
    name: "Ngozi Madu",
    picture: "https://randomuser.me/api/portraits/women/4.jpg",
    kingdom: "Obinze",
    location: {
      longitude: 6.999922042631105,

      latitude: 5.401756567461427,
    },
    username: "ngozi_madu",
  },
  {
    name: "Emeka Obi",
    picture: "https://randomuser.me/api/portraits/men/5.jpg",
    kingdom: "Umuchima",
    location: {
      longitude: 6.992222042631103,
      latitude: 5.391256567461425,
    },
    username: "emeka_obi",
  },
];

export const engineeringDepartments = [
  "Mechanical Engineering",
  "Civil Engineering",
  "Electrical/Electronic Engineering",
  "Computer Engineering",
  "Petroleum Engineering",
  "Chemical Engineering",
  "Agricultural Engineering",
  "Polymer&Textile Engineering",
];

// export const shops = [
//   {
//     id: 222,
//     name: "Campus Café",
//     description: "A cozy place for students to grab a coffee.",
//     longitude: 6.985572042631102,
//     latitude: 5.398606567461426,
//     size: 0.0007,
//     userId: 1,
//     owner: users[0],
//     category: "Eatery",
//     occupied: true,
//     requestedOrder: "",
//   },
//   // {
//   //   id: 383,
//   //   name: "Tech Gear",
//   //   description: "Electronic gadgets and accessories.",
//   //   longitude: 6.986972042631102,
//   //   latitude: 5.397906567461426,
//   //   userId: 2,
//   //   owner: users[1],
//   //   categoryId: 2,
//   // },
//   {
//     id: 300,
//     name: "Book Nook",
//     description: "Books and stationeries for students.",
//     longitude: 6.986272042631102,
//     latitude: 5.396506567461426,
//     size: 0.0007,
//     userId: 3,
//     owner: users[2],
//     category: "Education",
//     occupied: true,
//   },
//   {
//     id: 4,
//     name: "Fashion Hub",
//     description: "Trendy clothes and accessories.",
//     longitude: 5.397906567461426,
//     latitude: 6.989072042631102,
//     size: 0.0007,
//     userId: 4,
//     owner: users[3],
//     category: "Fashon & Design",
//     occupied: true,
//   },
//   {
//     id: 462,
//     name: "Gourmet Express",
//     description: "Fast food and snacks.",
//     longitude: 6.987672042631102,
//     latitude: 5.396506567461426,
//     size: 0.0007,
//     userId: 5,
//     owner: users[4],
//     category: "Eatery",
//     occupied: true,
//   },
//   {
//     id: 224,
//     name: "Green Grocer",
//     description: "Fresh fruits and vegetables.",
//     longitude: 6.985572042631102,
//     latitude: 5.400006567461427,
//     size: 0.0007,
//     userId: 1,
//     owner: users[1],
//     category: "Eatery",
//     occupied: true,
//   },
//   {
//     id: 541,
//     name: "Fit & Fab",
//     description: "Sports and fitness gear.",
//     longitude: 6.988372042631102,
//     latitude: 5.395106567461426,
//     size: 0.0007,
//     userId: 6,
//     owner: users[0],
//     category: "Fitness",
//     occupied: true,
//   },
//   {
//     id: 220,
//     name: "Beauty Boutique",
//     description: "Cosmetics and skincare products.",
//     longitude: 6.985572042631102,
//     latitude: 5.397206567461426,
//     size: 0.0007,
//     userId: 7,
//     owner: users[2],
//     category: "Fashion & Design",
//     occupied: true,
//   },
//   {
//     id: 1112,
//     name: "Campus Grill",
//     description: "Barbecue and grilled dishes.",
//     longitude: 6.993272042631103,
//     latitude: 5.397906567461426,
//     size: 0.0007,
//     userId: 4,
//     owner: users[3],
//     categoryId: 1,
//     category: "Eatery",
//     occupied: true,
//   },
//   {
//     id: 1221,
//     name: "Gadget World",
//     description: "Mobile phones and accessories.",
//     longitude: 6.993972042631103,
//     latitude: 5.396506567461426,
//     size: 0.0007,
//     userId: 2,
//     owner: users[4],
//     categoryId: 2,
//     category: "Gadgets & Home Appliances",
//     occupied: true,
//   },
// ];

// Example array of items with meaningful names
export const shopItems = [
  {
    title: "Electronics",
    items: [
      {
        id: "item1",
        name: "Wireless Headphones",
        price: 120,
        image: "/images/polo/orange.jpg",
      },
      {
        id: "item2",
        name: "Bluetooth Speaker",
        price: 80,
        image: "/images/polo/black.jpg",
      },
      {
        id: "item3",
        name: "Smartphone Case",
        price: 25,
        image: "/images/polo/boston.jpg",
      },
    ],
  },
  {
    title: "Computer Accessories",
    items: [
      {
        id: "item4",
        name: "Laptop Stand",
        price: 50,
        image: "/images/polo/dgreen.jpg",
      },
      {
        id: "item5",
        name: "USB-C Charger",
        price: 30,
        image: "/images/polo/light.jpg",
      },
      {
        id: "item6",
        name: "Mechanical Keyboard",
        price: 150,
        image: "/images/polo/mc.jpg",
      },
    ],
  },
  {
    title: "Gaming Gear",
    items: [
      {
        id: "item7",
        name: "Gaming Mouse",
        price: 45,
        image: "/images/polo/gaming_mouse.jpg",
      },
      {
        id: "item8",
        name: "External SSD (1TB)",
        price: 200,
        image: "/images/polo/external_ssd.jpg",
      },
    ],
  },
  {
    title: "Monitors",
    items: [
      {
        id: "item9",
        name: "4K Monitor",
        price: 300,
        image: "/images/polo/4k_monitor.jpg",
      },
    ],
  },
  {
    title: "Audio",
    items: [
      {
        id: "item10",
        name: "Noise-Cancelling Earbuds",
        price: 100,
        image: "/images/polo/noise_cancelling_earbuds.jpg",
      },
    ],
  },
];

export const orders = [
  {
    orderId: "ORD001",
    userID: "USER001",
    user: users[1],
    items: [
      { id: "ITEM001", name: "Laptop", quantity: 1, price: 999.99 },
      { id: "ITEM002", name: "Wireless Mouse", quantity: 2, price: 25.99 },
    ],
    totalAmount: 1051.97,
    orderDate: "2024-10-10",
    status: "Delivered",
  },
  {
    orderId: "ORD002",
    userId: "USER002",
    user: users[0],
    items: [
      { id: "ITEM003", name: "Smartphone", quantity: 1, price: 799.99 },
      { id: "ITEM004", name: "Phone Case", quantity: 3, price: 15.99 },
    ],
    totalAmount: 847.96,
    orderDate: "2024-10-09",
    status: "Shipped",
  },
  {
    orderId: "ORD003",
    userId: "USER003",
    user: users[2],
    items: [
      { id: "ITEM005", name: "Desk Chair", quantity: 1, price: 199.99 },
      { id: "ITEM006", name: "Desk Lamp", quantity: 1, price: 49.99 },
    ],
    totalAmount: 249.98,
    orderDate: "2024-10-08",
    status: "Processing",
  },
  {
    orderId: "ORD004",
    userId: "USER004",
    user: users[4],
    items: [
      { id: "ITEM007", name: "Running Shoes", quantity: 1, price: 129.99 },
      { id: "ITEM008", name: "Sports Socks", quantity: 5, price: 9.99 },
    ],
    totalAmount: 179.94,
    orderDate: "2024-10-07",
    status: "Delivered",
  },
  {
    orderId: "ORD005",
    userId: "USER005",
    user: users[3],
    items: [
      { id: "ITEM009", name: "Headphones", quantity: 1, price: 149.99 },
      { id: "ITEM010", name: "Portable Charger", quantity: 2, price: 19.99 },
    ],
    totalAmount: 189.97,
    orderDate: "2024-10-06",
    status: "Cancelled",
  },
];

export const status = [
  {
    id: 1,
    userName: "John Doe",
    caption: "Enjoying a sunny day at the park!",
    mediaUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 2,
    userName: "Jane Smith",
    caption: "Just finished a 5K run!",
    mediaUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 3,
    userName: "Alex Johnson",
    caption: "Grabbing a coffee to start the day ☕️",
    mediaUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 4,
    userName: "Emily Davis",
    caption: "Looking forward to the weekend!",
  },
  {
    id: 5,
    userName: "Michael Brown",
    caption: "Trying out a new recipe tonight!",
    mediaUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 6,
    userName: "Sarah Wilson",
    caption: "Lovely evening walk with the family.",
    mediaUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 7,
    userName: "Chris Martin",
    caption: "Nothing beats a good book.",
  },
];

export const userStatusUpdates = [
  {
    id: 1,
    userName: "John Doe",
    caption: "Enjoying a sunny day at the park!",
    mediaUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 2,
    userName: "John Doe",
    caption: "Just finished a 5K run!",
    mediaUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 3,
    userName: "John Doe",
    caption: "Grabbing a coffee to start the day ☕️",
    mediaUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 4,
    userName: "John Doe",
    caption: "Looking forward to the weekend!",
  },
];

export const shops = [
  {
    img: "/images/hyaman.jpg",
    brandTag: "[HEL]",
    brandName: "Hyaman Enterprise Limited",
    description: "All Kinds of Footwear",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[SHP]",
    brandName: "Superb Handicrafts Place",
    description: "Handmade Crafts and Gifts",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[QTQ]",
    brandName: "Quality Textiles Quarters",
    description: "Fabrics and Textiles",
    kingdom: "Umuchima",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[LCL]",
    brandName: "Local Cuisine Lounge",
    description: "Traditional Foods and Snacks",
    kingdom: "FUTO",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[BGS]",
    brandName: "Bright Gadgets Store",
    description: "Electronics and Gadgets",
    kingdom: "Obinze",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[STY]",
    brandName: "Stylish Trends",
    description: "Fashion and Accessories",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[BMS]",
    brandName: "Books and More Store",
    description: "Books and Stationery",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[PTP]",
    brandName: "Perfect Tech Plaza",
    description: "Tech Accessories and Services",
    kingdom: "Umuchima",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[FTW]",
    brandName: "Footwear World",
    description: "Shoes and Sandals",
    kingdom: "FUTO",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[HSH]",
    brandName: "Home Supplies Hub",
    description: "Home and Kitchen Supplies",
    kingdom: "Obinze",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[GSM]",
    brandName: "Grocery Store Market",
    description: "Groceries and Daily Needs",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[WLT]",
    brandName: "Wellness Therapy",
    description: "Health and Beauty Products",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[FDS]",
    brandName: "Fresh Dairy Store",
    description: "Dairy Products",
    kingdom: "Umuchima",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[SPG]",
    brandName: "Sports Gear",
    description: "Sports Equipment and Wear",
    kingdom: "FUTO",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[CLS]",
    brandName: "Classic Stationery",
    description: "Office and School Supplies",
    kingdom: "Obinze",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[HGS]",
    brandName: "Household Goods Store",
    description: "Household Items",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[PTS]",
    brandName: "Pet Supplies",
    description: "Pet Food and Accessories",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[BTL]",
    brandName: "Boutique Lane",
    description: "Fashion Boutique",
    kingdom: "Umuchima",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[KTS]",
    brandName: "Kitchen Tools Store",
    description: "Kitchenware and Utensils",
    kingdom: "FUTO",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[GRG]",
    brandName: "Garden Goods",
    description: "Gardening Tools and Plants",
    kingdom: "Obinze",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[FTL]",
    brandName: "Furnishing Trends",
    description: "Home Furnishings",
    kingdom: "Eziobodo",
  },
];
