export const sidebarLinks = [
  {
    imgURL: "/assets/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/assets/shop.svg",
    route: "/shops",
    label: "Stores",
  },

  {
    imgURL: "/assets/map.svg",
    route: "/map",
    label: "Map",
  },
  {
    imgURL: "/assets/user.svg",
    route: "/profile",
    label: "Profile",
  },

  {
    imgURL: "/assets/map.svg",
    route: "/map",
    label: "Map",
  },
  {
    imgURL: "/assets/user.svg",
    route: "/profile",
    label: "Profile",
  },
];

export const shops = [
  {
    img: "/images/hyaman.jpg",
    brandTag: "[HEL]",
    brandName: "Hyaman Enterprise Limited",
    description: "All Kinds of Footwear",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[SHP]",
    brandName: "Superb Handicrafts Place",
    description: "Handmade Crafts and Gifts",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[QTQ]",
    brandName: "Quality Textiles Quarters",
    description: "Fabrics and Textiles",
    kingdom: "Umuchima",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[LCL]",
    brandName: "Local Cuisine Lounge",
    description: "Traditional Foods and Snacks",
    kingdom: "FUTO",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[BGS]",
    brandName: "Bright Gadgets Store",
    description: "Electronics and Gadgets",
    kingdom: "Obinze",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[STY]",
    brandName: "Stylish Trends",
    description: "Fashion and Accessories",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[BMS]",
    brandName: "Books and More Store",
    description: "Books and Stationery",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[PTP]",
    brandName: "Perfect Tech Plaza",
    description: "Tech Accessories and Services",
    kingdom: "Umuchima",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[FTW]",
    brandName: "Footwear World",
    description: "Shoes and Sandals",
    kingdom: "FUTO",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[HSH]",
    brandName: "Home Supplies Hub",
    description: "Home and Kitchen Supplies",
    kingdom: "Obinze",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[GSM]",
    brandName: "Grocery Store Market",
    description: "Groceries and Daily Needs",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[WLT]",
    brandName: "Wellness Therapy",
    description: "Health and Beauty Products",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[FDS]",
    brandName: "Fresh Dairy Store",
    description: "Dairy Products",
    kingdom: "Umuchima",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[SPG]",
    brandName: "Sports Gear",
    description: "Sports Equipment and Wear",
    kingdom: "FUTO",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[CLS]",
    brandName: "Classic Stationery",
    description: "Office and School Supplies",
    kingdom: "Obinze",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[HGS]",
    brandName: "Household Goods Store",
    description: "Household Items",
    kingdom: "Eziobodo",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[PTS]",
    brandName: "Pet Supplies",
    description: "Pet Food and Accessories",
    kingdom: "Ihiagwa",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[BTL]",
    brandName: "Boutique Lane",
    description: "Fashion Boutique",
    kingdom: "Umuchima",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[KTS]",
    brandName: "Kitchen Tools Store",
    description: "Kitchenware and Utensils",
    kingdom: "FUTO",
  },
  {
    img: "/images/lorem.jpg",
    brandTag: "[GRG]",
    brandName: "Garden Goods",
    description: "Gardening Tools and Plants",
    kingdom: "Obinze",
  },
  {
    img: "/images/hyaman.jpg",
    brandTag: "[FTL]",
    brandName: "Furnishing Trends",
    description: "Home Furnishings",
    kingdom: "Eziobodo",
  },
];

export const shopCategories = [
  "Food & Beverage",
  "Clothing & Accessories",
  "Books & Stationery",
  "Electronics & Accessories",
  "Health & Beauty",
  "Events & Entertainment",
  "Secondhand Goods",
  "Services",
  "Tech Services",
];
